


services:

  web:
    image: nginx
    ports:
      - "8081:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
